name: GoldmanLocker
main: lee.code.locker.GoldmanLocker
version: ${project.version}
api-version: 1.19
author: Lee
commands:
  lock:
    description: Main command for locker plugin.
    permission: lock.command.lock
    usage: "/lock &f<command>"